1 patch
laipan009/java-shareit pull request #1
Opened 2024-01-27 20:23 UTC by laipan009

2024-01-28 06:26 UTC, Frilock requested changes
Оставил комментарии в коде

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error("Invoke exception " + e.getMessage());
можно двоеточие добавить

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +
Лишняя пустая строка

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                           @RequestHeader(value = "X-Sharer-User-Id") int userId) {
"X-Sharer-User-Id" литерал повторяется более двух раз - вынесите его в константу

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @Validated(OnUpdate.class) @RequestBody ItemDto itemDto,
Вы проверяли валидацию? Когда валидируете дто то надо использовать аннотацию Valid

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public ItemDto(Integer id, String name, String description, Boolean available, Integer request) {
У вас есть аннотация @AllArgsConstructor зачем тогда конструктор?

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public ItemDto(Integer id, String name, String description, Boolean available) {
Чтобы не делать конструкторы на все случаи жизни (так кстати не совсем верно), лучше повесьте аннотацию @RequiredArgsConstructor

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        if (itemDto.getAvailable() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        if (itemDto.getName() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        return itemDto1;
Числовые префиксы и окончания, являются плохой практикой, лучше просто измените переменную, например, updateditem и т.д. 
В данном случае можно просто return ItemMapper.to....

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +                .filter(item -> item.getName().toLowerCase().contains(text.toLowerCase())
Используйте StringUtils.containsIgnoreCase

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +    public List<Item> getItemsByUserId(int userId) {
Отсутствует @Override

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/User.java
> +    public User(String name, String email) {
RequiredArgsConstructor

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User partialUpdateUser(@PathVariable("userId") int userId, @RequestBody UserDto userDto) {
Литерал в пути повторяется более 2х раз - вынесите в константу

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +        if (userDto.getName() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2024-01-28 06:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    private final UserStorageImpl userStorageImpl;
Инжектить в класс нужно интерфейс, а не реализацию

2024-01-28 13:34 UTC, laipan009 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @Validated(OnUpdate.class) @RequestBody ItemDto itemDto,
Использовал  @Validated, так как при создании нового item поля name, description, available должны быть не null и к ним применяю groups = OnCreate.class, а при обновлении нет пока по ТЗ требований и поэтому по сути в этом поле ничего не валидирутеся, но используется один и тот же ДТО класс, но с возможностью создавать разные группы валидации.

2024-01-28 19:32 UTC, Frilock requested changes
Добрый вечер, еще ряд комментариев

2024-01-28 19:32 UTC, Frilock commented on pom.xml
> +			<version>3.12.0</version>
Версию в properties

2024-01-28 19:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final String HEADER_WITH_OWNER_ID = "X-Sharer-User-Id";
static

2024-01-28 19:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .request(item.getRequest() != null? item.getRequest().getId() : null)
перед ? пробел

2024-01-28 19:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        return itemAfterMapping;
Можно в 1 строчку

2024-01-28 19:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +        if (Optional.ofNullable(userDto.getName()).isPresent()) {
Не, Optional.ofNullable(userDto.getName()).ifPresent(existingUser::setEmail)

2024-01-28 20:49 UTC, laipan009 commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +        if (Optional.ofNullable(userDto.getName()).isPresent()) {
Понял, так явно лаконичнее и читабельнее сразу становится метод) спасибо)

2024-01-29 17:15 UTC, Frilock approved these changes
Принято

2024-02-10 10:49 UTC, merged